--1. 강의별 수강생 수 구하기
SELECT TITLE, COUNT(NVL(LECTURE_ID,0))
FROM ENROLLMENT
JOIN LECTURE USING(LECTURE_ID)
GROUP BY TITLE;
        
        
--2. 특정 학생의 수강 내역 조회
SELECT TITLE, NAME, STATUS
FROM  LECTURE
JOIN TEACHER USING (TEACHER_ID)
JOIN ENROLLMENT USING (LECTURE_ID)
WHERE STUDENT_ID = '1001' AND STATUS = 'Y';

--3. 전공별 강의 개수 집계
SELECT SUBJECT, COUNT(SUBJECT)
FROM TEACHER
WHERE SUBJECT IS NOT NULL
GROUP BY SUBJECT
ORDER BY SUBJECT;

--4. 평균 점수가 80점 이상인 강의만 조회
SELECT TITLE, AVG(GRADE_SCORE)
FROM ENROLLMENT
JOIN LECTURE USING (LECTURE_ID)
GROUP BY TITLE
HAVING AVG(GRADE_SCORE) >=80
ORDER BY AVG(GRADE_SCORE) DESC;

--5. 수강기록 등록 시, 강의별 수강 인원 수 자동 트리거
CREATE OR REPLACE TRIGGER TRG_01
AFTER INSERT
ON ENROLLMENT
BEGIN
IF(ENROLLMENT = :NEW.ENROLLMENT)
 THEN UPDATE LECTURE
 
  SET INDEX_COUNT = INDEX_COUNT + 1
   WHERE ENROLL_ID = (:NEW ENROLL_ID);
ELSE
 UPDATE LECTURE
    SET INDEX_COUNT = INDEX_COUNT - 1
        WHERE ENROLL_ID = (:NEW ENROLL_ID);
        END IF;
    END;

