-- JDBC 개인 실습용 SQL
DROP TABLE RENTAL;
DROP TABLE MEMBER;
DROP TABLE BOOK;

CREATE TABLE BOOK(
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    AUTHOR VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(50)
    );
    
DROP TABLE BOOK;

CREATE TABLE MEMBER(
    MEMBER_ID NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20)
);

CREATE TABLE RENTAL(
    RENTAL_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    RENTAL_DATE DATE DEFAULT SYSDATE,
    RETURN_DATE DATE,
    CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_RENTAL_BOOK FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

CREATE SEQUENCE SEQ_BOOK_ID
NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_ID
NOCACHE;
CREATE SEQUENCE SEQ_RENTAL_ID
NOCACHE;

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL,'김민수','010-1111-2222');

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL,'최수빈','010-2222-3333');

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_ID.NEXTVAL,'박지민','010-4444-5555');

INSERT INTO RENTAL
VALUES(SEQ_RENTAL_ID.NEXTVAL,1,1,SYSDATE,NULL);

INSERT INTO RENTAL
VALUES(SEQ_RENTAL_ID.NEXTVAL,2,3,SYSDATE-10,SYSDATE-3);

COMMIT;