--1. 영어영문학과 학생들의 학번과 이름, 입학년도를 입학년도가 빠른 순서대로 표시
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과'
ORDER BY ENTRANCE_DATE;

--2. 춘 기술대학교의 교수 중 이름이 세글자가 아닌 교수의 이름과 주민번호
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3. 춘기술대학교의 남자교수들의 이름과 나이를 출력
-- 나이가 적은 순에서 많은 순으로, 나이는 만으로 계산
SELECT PROFESSOR_NAME, EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN, 1, 2)) "나이"
FROM TB_PROFESSOR
ORDER BY 나이;

--4. 교수들의 이름 중 성을 제외한 이름만 출력
SELECT SUBSTR(PROFESSOR_NAME,2) "이름"
FROM TB_PROFESSOR;

--5. 춘 기술대학교의 재수생 입학자
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR  FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) > 19;

SELECT EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)))
FROM TB_STUDENT;

--6. 2020년 크리스마스는 무슨 요일인가
SELECT TO_CHAR(TO_DATE('20201225'), 'DAY')
FROM DUAL;

--7. 2099년 10월 11일, 2049년
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY'),
       TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY')
FROM DUAL;

--8. 춘 기술대학교의 2000년도 이전 학번의 학생들의 학번과 이름
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9. 학번이 A517178인 한아름 학생의 학점 총 평점
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10. 학과별 학생수를 구하여 학과번호, 학생수의 형태로 결과 출력
SELECT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11. 지도교수를 배정받지 못한 학생 수
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 학번이 A112113인 김고운 학생의 년도 별 평점
SELECT SUBSTR(TERM_NO,1,4) "년도", ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);


--13. 학과 별 휴학생의 학과코드명과 휴학생 수
SELECT DEPARTMENT_NO "학과코드명", COUNT(DECODE(ABSENCE_YN,'Y',1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 춘대학교에 다니는 동명이인의 학생들의 이름 찾기
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) != '1'
ORDER BY STUDENT_NAME;

--15. 학번이 A112113인 김고운 학생의 년도, 학기 별 평점과 년도 별 누적 평점, 총 평점
SELECT SUBSTR(TERM_NO,1,4) "년도", SUBSTR(TERM_NO,5) "학기", ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO
ORDER BY TERM_NO;














