--1. 학생 이름과 주소지 표시
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2. 휴학 중인 학생들의 이름과 주민번호를 나이가 적은 순서로 화면에 출력
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
ORDER BY STUDENT_SSN DESC;

--3. 주소지가 강원도나 경기도인 학생들 중 1900년도 학번을 가진 학생 이름, 학번, 주소를 이름의 오름차순
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE ('강원%') OR STUDENT_ADDRESS LIKE('경기%');

--4. 현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인할 수 있는 문장 작성
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
ORDER BY SUBSTR(PROFESSOR_SSN,1,6);

--5. 2004년 2학기에 C3118100 과목을 수강한 학생들의 학점을 조회하려고 한다
-- 학점이 높은 학생부터 표시, 학점이 같으면 학번이 낮은 학생부터 표시하는 구문
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO ='C3118100'
ORDER BY POINT DESC, STUDENT_NO;

--6. 학생번호, 이름, 학과이름을 학생이름으로 오름차순 정렬
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7. 춘 기술대학교의 과목 이름과 과목의 학과 이름을 출력하라
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY CLASS_NAME, DEPARTMENT_NAME;

--8. 과목 이름과 교수 이름 출력
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
ORDER BY CLASS_NAME, PROFESSOR_NAME;

--9. 8번의 결과 중 인문사회 계열에 속한 과목의 교수 이름
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY CLASS_NAME, PROFESSOR_NAME;

--10. 음악학과 학생들의 학번, 학생 이름, 전체 평점
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING DEPARTMENT_NAME = '음악학과';

--11. 학번이 A313047인 학생의 학과 이름, 학생 이름, 지도교수이름
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(PROFESSOR_NO =  COACH_PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12. 2007년에 인간관계론을 수강한 학생을 찾아 학생이름과 수강학기를 표시
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%';

----------------------여기부터 다시 해보기 ------------------------------------

--13. 예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목
-- 과목 이름과 학과 이름 출력
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--14. 서반아어학과 학생이름과 지도교수 이름 출력
--(지도교수가 없는 학생이면 지도교수 미지정으로 표시, 고학번 학생이 먼저 표시)
SELECT STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME,'지도교수 미지정')"지도 교수"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE;

--15. 휴학생이 아닌 학생 중 평점이 4.0 이상인 학생의 학번, 이름, 학과 이름, 평점
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;


--16. 환경조경학과 전공과목들의 과목 별 평점 
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY CLASS_NO, CLASS_NAME, DEPARTMENT_NAME
HAVING DEPARTMENT_NAME = '환경조경학과';

--17. 최경희 학생과 같은 과 학생들의 이름과 주소 출력
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
        FROM TB_STUDENT 
        WHERE STUDENT_NAME = '최경희');
        
--18. 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
      FROM TB_GRADE
           JOIN TB_STUDENT USING(STUDENT_NO)
      WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                             FROM TB_DEPARTMENT
                             WHERE DEPARTMENT_NAME = '국어국문학과')
    GROUP BY STUDENT_NO, STUDENT_NAME
    ORDER BY AVG(POINT) DESC)
WHERE ROWNUM =1;

    

--19. 